<a href="https://colab.research.google.com/github/venkatesh-manikumar/Datascience-Assignments/blob/main/Numpy_Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

1.	Create a 2D array and print the dim and shape

In [14]:
np_array = np.arange(1,5).reshape(2,2)
print(type(np_array))
print('Shape = ',np_array.shape)
print('Dimension = ',np_array.ndim)


<class 'numpy.ndarray'>
Shape =  (2, 2)
Dimension =  2


2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [25]:
data = np.arange(1,21)
slicing = slice(9,15,1)

# METHOD 1
data[slicing]

array([10, 11, 12, 13, 14, 15])

In [23]:
# METHOD 2
data[10:15]

array([11, 12, 13, 14, 15])

In [29]:
# Result will not get stored need to assign to variable to store its state.
print(data)
part = data[10:15]
part

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([11, 12, 13, 14, 15])

3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using

  1.   Addition
  2.   Subtraction
  3.   Multiplication
  4.   Division





In [39]:
a = np.arange(1,36).reshape(7,5)
b = np.arange(1,36).reshape(7,5)

print(a + b)
print(type(a+b))

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]]
<class 'numpy.ndarray'>


In [40]:
print(a + b)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]]


In [41]:
print(a * b)

[[   1    4    9   16   25]
 [  36   49   64   81  100]
 [ 121  144  169  196  225]
 [ 256  289  324  361  400]
 [ 441  484  529  576  625]
 [ 676  729  784  841  900]
 [ 961 1024 1089 1156 1225]]


In [43]:
print(a // b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


4.	Create 2 incompatible arrays for broadcast and print out the error

In [49]:
x = np.arange(1,5).reshape(2,2)
y = np.arange(1,5).reshape(4,1)

x + y  # "ValueError: operands could not be broadcast together with shapes (2,2) (4,1) "

ValueError: ignored

5.	Create two arrays of any dimension and perform vstack and hstack

In [113]:
x = np.arange(1,7).reshape(3,2)
y = np.arange(-10,-16,-1).reshape(3,2)

print("2D ARRAY OF DIMENSION 3x2")
print(x)
print("2D ARRAY OF DIMENSION 3x2")
print(y)
print("VSTACK() RESULT OF DIMENSION 6x2")
print(np.vstack((x,y)))
print("SHAPE",np.vstack((x,y)).shape)
print("DIMENSION",np.vstack((x,y)).ndim)

2D ARRAY OF DIMENSION 3x2
[[1 2]
 [3 4]
 [5 6]]
2D ARRAY OF DIMENSION 3x2
[[-10 -11]
 [-12 -13]
 [-14 -15]]
VSTACK() RESULT OF DIMENSION 6x2
[[  1   2]
 [  3   4]
 [  5   6]
 [-10 -11]
 [-12 -13]
 [-14 -15]]
SHAPE (6, 2)
DIMENSION 2


In [112]:
print("2D ARRAY OF DIMENSION 3x2")
print(x)
print("2D ARRAY OF DIMENSION 3x2")
print(y)
print("HSTACK() RESULT OF DIMENSION 3x4")
print(np.hstack((x,y)))
print("SHAPE",np.vstack((x,y)).shape)
print("DIMENSION",np.vstack((x,y)).ndim)

2D ARRAY OF DIMENSION 3x2
[[1 2]
 [3 4]
 [5 6]]
2D ARRAY OF DIMENSION 3x2
[[-10 -11]
 [-12 -13]
 [-14 -15]]
HSTACK() RESULT OF DIMENSION 3x4
[[  1   2 -10 -11]
 [  3   4 -12 -13]
 [  5   6 -14 -15]]
SHAPE (6, 2)
DIMENSION 2


6.	Append two arrays using axis = 0 and axis = 1

In [117]:
print("2D ARRAY OF DIMENSION 3x2")
print(x)
print("2D ARRAY OF DIMENSION 3x2")
print(y)
print("Append() RESULT OF DIMENSION 6x2")
print(np.append(x,y,axis=0))

print("SHAPE",np.append(x,y,axis = 0).shape)
print("DIMENSION",np.append(x,y,axis = 0).ndim)

2D ARRAY OF DIMENSION 3x2
[[1 2]
 [3 4]
 [5 6]]
2D ARRAY OF DIMENSION 3x2
[[-10 -11]
 [-12 -13]
 [-14 -15]]
Append() RESULT OF DIMENSION 6x2
[[  1   2]
 [  3   4]
 [  5   6]
 [-10 -11]
 [-12 -13]
 [-14 -15]]
SHAPE (6, 2)
DIMENSION 2


In [118]:
print("2D ARRAY OF DIMENSION 3x2")
print(x)
print("2D ARRAY OF DIMENSION 3x2")
print(y)
print("Append() RESULT OF DIMENSION 3x4")
print(np.append(x,y,axis=1))

print("SHAPE",np.append(x,y,axis = 1).shape)
print("DIMENSION",np.append(x,y,axis = 1).ndim)

2D ARRAY OF DIMENSION 3x2
[[1 2]
 [3 4]
 [5 6]]
2D ARRAY OF DIMENSION 3x2
[[-10 -11]
 [-12 -13]
 [-14 -15]]
Append() RESULT OF DIMENSION 3x4
[[  1   2 -10 -11]
 [  3   4 -12 -13]
 [  5   6 -14 -15]]
SHAPE (3, 4)
DIMENSION 2


7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [152]:
pd.DataFrame(np.array([ range(1,5),
                        range(-5,-9,-1),
                        range(1,5),
                        range(-5,-9,-1),
                        range(1,5),
                        range(-5,-9,-1),
                        range(1,5),
                        range(-5,-9,-1)
                         ]) , columns = ['a','b','c','d'] ).head()

a  b  c  d
0  1  2  3  4
1 -5 -6 -7 -8
2  1  2  3  4
3 -5 -6 -7 -8
4  1  2  3  4

8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [244]:
dict_data = dict(state= ['Tamilnadu','Telangana','Karanataka','Goa'], 
                 capital= ['Chennai','Hyderabad','Bangalore','Panaji'], 
                 street_count= [80,50,np.nan,90], 
                 No_of_schools= [100,200,np.nan,105],
                 languages = ['Tamil','Telegu','Kannada',np.nan],
                 population = [500000,80000,12968,756214],
                 area = ['15000 sqkm','5222 sqkm','8456 sqkm','3648 sqkm'],
                 literacy_rate = ['70%','80%',np.nan,np.nan])

df_data = pd.DataFrame(dict_data).head()

df_data

state    capital  street_count  No_of_schools languages  population  \
0   Tamilnadu    Chennai          80.0          100.0     Tamil      500000   
1   Telangana  Hyderabad          50.0          200.0    Telegu       80000   
2  Karanataka  Bangalore           NaN            NaN   Kannada       12968   
3         Goa     Panaji          90.0          105.0       NaN      756214   

         area literacy_rate  
0  15000 sqkm           70%  
1   5222 sqkm           80%  
2   8456 sqkm           NaN  
3   3648 sqkm           NaN

9.	Use loc and iloc to subset the data for the above dataframe

In [178]:
df_data.iloc[[0],[1,2,3]]  # INDEX BASED SELECTION
df_data.iloc[0:3,0:8]

state    capital  street_count  No_of_schools languages  population  \
0   Tamilnadu    Chennai            80            100     Tamil      500000   
1   Telangana  Hyderabad            50            200    Telegu       80000   
2  Karanataka  Bangalore            30            300   Kannada       12968   

         area literacy_rate  
0  15000 sqkm           70%  
1   5222 sqkm           80%  
2   8456 sqkm           60%

In [198]:
df_data.loc[-1:, ['state','capital','street_count']]  # LABEL BASED SELECTION

state    capital  street_count
0   Tamilnadu    Chennai            80
1   Telangana  Hyderabad            50
2  Karanataka  Bangalore            30
3         Goa     Panaji            90

10.	How to check the total number of not null values in a column?

In [239]:
df_data[~ df_data.literacy_rate.isna()].literacy_rate.count()

df_data.literacy_rate.notnull().sum()

df_data.loc[df_data.literacy_rate.notnull()].literacy_rate.count()

df_data.literacy_rate.value_counts().count()

2

11.	Create a dataframe with missing values and fill them all with 100

In [291]:
df_data.select_dtypes(include=[np.number]).fillna('100')

street_count No_of_schools  population
0         80.0         100.0      500000
1         50.0         200.0       80000
2          100           100       12968
3         90.0         105.0      756214

12.	Create a dataframe with missing values and drop the null records

In [296]:
df_data.dropna(axis = 0)

state    capital  street_count  No_of_schools languages  population  \
0  Tamilnadu    Chennai          80.0          100.0     Tamil      500000   
1  Telangana  Hyderabad          50.0          200.0    Telegu       80000   

         area literacy_rate  
0  15000 sqkm           70%  
1   5222 sqkm           80%

In [297]:
df_data.dropna(axis = 1)

state    capital  population        area
0   Tamilnadu    Chennai      500000  15000 sqkm
1   Telangana  Hyderabad       80000   5222 sqkm
2  Karanataka  Bangalore       12968   8456 sqkm
3         Goa     Panaji      756214   3648 sqkm

13.	Perform following aggregation task on below table
  1.   Get the average age group by Region
  2.   Get the sum of Age and Validation group by Hair color and then reset the index
  3.Get the mean and the median of Age group by Region



In [305]:
data = dict(Age=[25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23],
Hair_Color=['Black','Black','Red','Blond','Brown','Brown','Black','Brown', 'Blond','Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
US_Region=['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast','Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
Validation=[1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1])

data_points = pd.DataFrame(data)

In [318]:
data_points.groupby('US_Region').Age.mean()

US_Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

In [333]:
data_points.groupby('Hair_Color')['Age','Validation'].sum().reset_index()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


Hair_Color  Age  Validation
0      Black  229           4
1      Blond  101           2
2      Brown  170           1
3        Red   45           1

In [334]:
data_points.groupby('US_Region').Age.agg(['median','mean'])

median       mean
US_Region                   
Northeast    31.0  32.750000
Northwest    40.5  40.500000
Southeast    25.5  31.000000
Southwest    25.0  29.857143

14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [358]:
half_count = len(data_points)//2

df1_left = data_points.iloc[:half_count , :]

df2_right = data_points.iloc[half_count: , :].reset_index()


In [379]:
pd.merge(df1_left , df2_right , on = ['US_Region'] , how = 'inner')
pd.merge(df1_left , df2_right , on = ['US_Region'] , how = 'left')
pd.merge(df1_left , df2_right , on = ['US_Region'] , how = 'right')

Age_x Hair_Color_x  US_Region  Validation_x  Age_y Hair_Color_y  \
0      25        Black  Southwest             1     21        Blond   
1      35        Blond  Southwest             0     21        Blond   
2      33        Brown  Southwest             0     21        Blond   
3      25        Black  Southwest             0     21        Blond   
4      45          Red  Northeast             1     24        Blond   
5      35        Brown  Northeast             0     24        Blond   
6      25        Black  Southwest             1     48        Black   
7      35        Blond  Southwest             0     48        Black   
8      33        Brown  Southwest             0     48        Black   
9      25        Black  Southwest             0     48        Black   
10     25        Black  Southwest             1     22        Black   
11     35        Blond  Southwest             0     22        Black   
12     33        Brown  Southwest             0     22        Black   
13     25        Black  Southwest             0     22        Black   
14     45          Red  Northeast             1     27        Brown   
15     35        Brown  Northeast             0     27        Brown   
16     52        Brown  Southeast             0     28        Black   
17     52        Brown  Southeast             0     21        Blond   
18     30        Black  Northwest             1     51        Black   
19     52        Brown  Southeast             0     23        Brown   

    Validation_y  
0              1  
1              1  
2              1  
3              1  
4              0  
5              0  
6              1  
7              1  
8              1  
9              1  
10             0  
11             0  
12             0  
13             0  
14             0  
15             0  
16             1  
17             1  
18             0  
19             1

15.	Split the below table and perform concat row wise and column wise

In [382]:
half_count = len(data_points)//2

df1_left = data_points.iloc[:half_count , :]

df2_right = data_points.iloc[half_count: , :]

pd.concat([df1_left,df2_right] , axis=0)


Age Hair_Color  US_Region  Validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [381]:
pd.concat([df1_left,df2_right] , axis=1)

Age Hair_Color  US_Region  Validation   Age Hair_Color  US_Region  \
0   25.0      Black  Southwest         1.0   NaN        NaN        NaN   
1   30.0      Black  Northwest         1.0   NaN        NaN        NaN   
2   45.0        Red  Northeast         1.0   NaN        NaN        NaN   
3   35.0      Blond  Southwest         0.0   NaN        NaN        NaN   
4   33.0      Brown  Southwest         0.0   NaN        NaN        NaN   
5   35.0      Brown  Northeast         0.0   NaN        NaN        NaN   
6   25.0      Black  Southwest         0.0   NaN        NaN        NaN   
7   52.0      Brown  Southeast         0.0   NaN        NaN        NaN   
8    NaN        NaN        NaN         NaN  21.0      Blond  Southwest   
9    NaN        NaN        NaN         NaN  24.0      Blond  Northeast   
10   NaN        NaN        NaN         NaN  48.0      Black  Southwest   
11   NaN        NaN        NaN         NaN  22.0      Black  Southwest   
12   NaN        NaN        NaN         NaN  27.0      Brown  Northeast   
13   NaN        NaN        NaN         NaN  28.0      Black  Southeast   
14   NaN        NaN        NaN         NaN  21.0      Blond  Southeast   
15   NaN        NaN        NaN         NaN  51.0      Black  Northwest   
16   NaN        NaN        NaN         NaN  23.0      Brown  Southeast   

    Validation  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          1.0  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0