<a href="https://colab.research.google.com/github/venkatesh-manikumar/Datascience-Assignments/blob/main/Numpy_Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

1.	Create a 2D array and print the dim and shape

In [14]:
np_array = np.arange(1,5).reshape(2,2)
print(type(np_array))
print('Shape = ',np_array.shape)
print('Dimension = ',np_array.ndim)


<class 'numpy.ndarray'>
Shape =  (2, 2)
Dimension =  2


2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [25]:
data = np.arange(1,21)
slicing = slice(9,15,1)

# METHOD 1
data[slicing]

array([10, 11, 12, 13, 14, 15])

In [23]:
# METHOD 2
data[10:15]

array([11, 12, 13, 14, 15])

In [29]:
# Result will not get stored need to assign to variable to store its state.
print(data)
part = data[10:15]
part

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([11, 12, 13, 14, 15])

3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using

  1.   Addition
  2.   Subtraction
  3.   Multiplication
  4.   Division





In [39]:
a = np.arange(1,36).reshape(7,5)
b = np.arange(1,36).reshape(7,5)

print(a + b)
print(type(a+b))

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]]
<class 'numpy.ndarray'>


In [40]:
print(a + b)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]]


In [41]:
print(a * b)

[[   1    4    9   16   25]
 [  36   49   64   81  100]
 [ 121  144  169  196  225]
 [ 256  289  324  361  400]
 [ 441  484  529  576  625]
 [ 676  729  784  841  900]
 [ 961 1024 1089 1156 1225]]


In [43]:
print(a // b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


4.	Create 2 incompatible arrays for broadcast and print out the error

In [49]:
x = np.arange(1,5).reshape(2,2)
y = np.arange(1,5).reshape(4,1)

x + y  # "ValueError: operands could not be broadcast together with shapes (2,2) (4,1) "

ValueError: ignored